on:
  workflow_dispatch:
    branches: [ main ]

name : demo-workflow-sa1

jobs:
  job1:
    environment: dev
    name: myjob1
    runs-on: ubuntu-latest
  
    steps:
    - name: Very Simple Hello World
      uses: phwes/simple_hello_world@v1
      
  job2:
    needs: job1
    name: myjob2
    runs-on: ubuntu-latest
  
    steps:
    - name: Very Simple Hello World
      uses: phwes/simple_hello_world@v1
